### ISSUE TITLE
Implement hasValue and anon class assertion mappings

### ISSUE THREAD

**Issue by cmungall** [geneontology/obographs#12]
Dependent on agreement on #7 

These have yet to be implemented:

```
Class: C
  SubClassOf: P value J

==>

edges:
 - subj: C
   pred: P
   obj: J
```

```
Individual: I
  Types: C

==>

edges:
 - subj: I
   pred: type
   obj: C
```
