### ISSUE TITLE
Null pointer with Node.getType()

### ISSUE THREAD

**Issue by pnrobinson** [geneontology/obographs#37]
I am using phenol (https://github.com/monarch-initiative/phenol) to parse the example GO obo file in that repository. It seems to be picking up this as a Node:
```
synonymtypedef: syngo_official_label "label approved by the SynGO project"
```
This is leading to a null error, in the debugger, I can see that the "type" attribute of the corresponding node object is null.

**Comment by pnrobinson** [comment]
![obographerror](https://user-images.githubusercontent.com/4943420/40940540-2100e630-6816-11e8-9f7a-804cebe433c8.png)

**Comment by pnrobinson** [comment]
Please leave a message here
https://github.com/monarch-initiative/phenol/issues/92
if this issue can be addressed.

**Comment by julesjacobsen** [comment]
Hi @pnrobinson, this is already fixed in 0.3.1 and in the official [go.json](http://purl.obolibrary.org/obo/go.json)

```yaml
- id: "http://purl.obolibrary.org/obo/go#syngo_official_label"
    lbl: "label approved by the SynGO project"
    type: "PROPERTY"
```
