### ISSUE TITLE
genus-differentia logicalDefinitionAxioms should have one or more restrictions

### ISSUE THREAD

**Issue by cmungall** [geneontology/obographs#75]
it looks like

**Comment by julesjacobsen** [comment]
@cmungall can you give an example of the OWL input and expected YAML output for this issue? The example you gave appears to have these.

```yaml
 logicalDefinitionAxioms:
  - definedClassId: "http://purl.obolibrary.org/obo/CL_0000005"
    genusIds:
    - "http://purl.obolibrary.org/obo/CL_0000057"
    restrictions:
    - propertyId: "http://purl.obolibrary.org/obo/RO_0002202"
      fillerId: "http://purl.obolibrary.org/obo/CL_0000333"
  - definedClassId: "http://purl.obolibrary.org/obo/CL_0000014"
    genusIds:
    - "http://purl.obolibrary.org/obo/CL_0000039"
    restrictions:
    - propertyId: "http://purl.obolibrary.org/obo/RO_0002215"
      fillerId: "http://purl.obolibrary.org/obo/GO_0017145"
```
