### ISSUE TITLE
Add a prefixes header

### ISSUE THREAD

**Issue by cmungall** [geneontology/obographs#97]
Consistent with other RDF serializations we should add a prefixes header

```yaml
  prefixes:
    slot_uri: sh:declare
    range: PrefixDeclaration
    multivalued: true
    inlined: true
    description: >-
      A collection of mappings between prefixes and namespaces, used to map CURIEs (e.g. GO:0008150) to
      IRIs (e.g. http://purl.obolibrary.org/obo/GO_0008150)
```

range:

```yaml
  PrefixDeclaration:
    class_uri: sh:PrefixDeclaration
    description: >-
      A mapping between an individual prefix (e.g. GO) and a namespace (e.g. http://purl.obolibrary.org/obo/GO_)
    attributes:
      prefix:
        key: true
        slot_uri: sh:prefix
        description: The prefix of a prefix declaration.
        range: string
        comments:
          - It is strongly recommended that the prefix is a valid NCName
      namespace:
        slot_uri: sh:namespace
        description: The namespace associated with a prefix in a prefix declaration.
        range: uri
```

**Comment by matentzn** [comment]
This is another very important issue for now.

**Comment by julesjacobsen** [comment]
So this in on the Graph object?

```yaml
graphDocument:
  graphs:
    - graph:
        id: hp
        prefixes:
            - prefix: "HP"
              namespace: "http://purl.obolibrary.org/obo/HP_"
```
